export const Roadmap = [
    {
        id:"4jFbQ9ZmW8V7",
        title: 'AI Engineer',
        description: 'Create smart systems that learn from data and make decisions to solve real-world problems.',
        href:"/aiengineer",
        duration: 'Varies',
        price: 19,
        completed: false,
        buy: false,
    },
    {
        id:"H6bE7cLxA2P9",
        title: 'Data Scientist',
        description: 'Data scientists analyze complex data to uncover insights that drive decision-making and innovation.',
        href:"/datascientist",
        duration: 'Varies',
        price: 19,
        completed: false,
        buy: false,
    },
    {
        id:"n8R4zK3Yt5Q1",
        title: 'MERN stack',
        description: 'Full-stack development framework combining MongoDB, Express.js, React, and Node.js.',
        href:"/mernstack",
        duration: 'Varies',
        price: 19,
        completed: false,
        buy: false,
    },
    {
        id:"d2F7pL6nW0Z9",
        title: 'Nextjs',
        description: 'Next.js: React framework for server-rendered React applications.',
        href:"/nextjs",
        duration: 'Varies',
        price: 19,
        completed: false,
        buy: false,
    },
];
